version: '3.8'
services:
  client:
    container_name: admin
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 4000:4000
    networks:
      - sefidsia-network
      
networks:
  sefidsia-network:
    driver: bridge      